class ftest
{
    int i=0;
    void frequency(int a[],int b)
    {
        int count=0;
        min m=new min();
        for(i=31;i>26;i--)
        {
            if(a[i]==m.c1[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c2[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c3[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c4[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c5[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c6[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c7[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c8[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c9[i])
            {
                count++;
            }
        }
        for(i=31;i<26;i--)
        {
            if(a[i]==m.c10[i])
            {
                count++;
            }
        }
        m.f1[b]=count;
    }
}